openapi: 3.1.0
info:
  title: Level of Trust Assessment Function API
  description: This API describes services offered by LoTAF
  contact:
    name: Jose Maria Jorquera Valero
    url: https://cyberdatalab.um.es/josemaria-jorquera/
    email: josemaria.jorquera@um.es
  version: 1.0.0
paths:
  /trust_management_LoTAF:
    get:
      tags:
        - monitoring
      summary: Get trust scores
      description: Retrieve trust scores from the available computation nodes
      operationId: get_trust_scores_trust_management_LoTAF_get
      parameters:
        - name: input_string
          in: query
          required: true
          schema:
            type: string
            title: Input String
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trust_Score_Response'
                title: Response Get Trust Scores Trust Management Lotaf Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/trust_management:
    get:
      tags:
        - api
      summary: Trust Management Function
      operationId: trust_management_route_api_trust_management_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Trust_Score_Response:
      properties:
        id:
          type: string
          title: Id
        trust_index:
          type: number
          title: Trust Index
      type: object
      required:
        - id
        - trust_index
      title: Trust_Score_Response
      id: uuid1
      trust_index: 0.4
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
